import logging
import handler  # This will be generated by Zappa
import worker


logging.basicConfig()
logger = logging.getLogger('app')


def lambda_handler(event, context):
    if is_lex_message(event):
        return worker.lex(event, None)
    return handler.lambda_handler(event, context)


def is_lex_message(event):
    invocation_sources = ['DialogCodeHook', 'FulfillmentCodeHook']
    return event and event.get('invocationSource') in invocation_sources
