import logging
from utils.config import CONFIG
import handler as zappa_handler  # This will be generated by Zappa
import worker


logging.basicConfig()


def handler(event, context):
    log_level = logging.getLevelName(CONFIG['log_level'])
    logging.basicConfig(level=log_level)

    if is_lex_message(event):
        return worker.lex(event, None)
    return zappa_handler.lambda_handler(event, context)


def is_lex_message(event):
    invocation_sources = ['DialogCodeHook', 'FulfillmentCodeHook']
    return event and event.get('invocationSource') in invocation_sources
